package model

type StockInfoEntity struct {
	stkCd         string `db:"stk_cd"`
	stkNm         string `db:"stk_nm"`
	setlMm        string `db:"setl_mm"`
	fav           string `db:"fav"`
	cap           string `db:"cap"`
	floStk        string `db:"flo_stk"`
	crdRt         string `db:"crd_rt"`
	oyrHgst       string `db:"oyr_hgst"`
	oyrLwst       string `db:"oyr_lwst"`
	mac           string `db:"mac"`
	macWght       string `db:"mac_wght"`
	forExhRt      string `db:"for_exh_rt"`
	replPric      string `db:"repl_pric"`
	per           string `db:"per"`
	eps           string `db:"eps"`
	roe           string `db:"roe"`
	pbr           string `db:"pbr"`
	ev            string `db:"ev"`
	bps           string `db:"bps"`
	saleAmt       string `db:"sale_amt"`
	busPro        string `db:"bus_pro"`
	cupNga        string `db:"cup_nga"`
	hgst          string `db:"250hgst"`
	lwst          string `db:"250lwst"`
	highPric      string `db:"high_pric"`
	openPric      string `db:"open_pric"`
	lowPric       string `db:"low_pric"`
	uplPric       string `db:"upl_pric"`
	lstPric       string `db:"lst_pric"`
	basePpric     string `db:"base_pric"`
	expCntrPric   string `db:"exp_cntr_pric"`
	expCntrQty    string `db:"exp_cntr_qty"`
	hgstPricDt    string `db:"250hgst_pric_dt"`
	hgstPricPreRt string `db:"250hgst_pric_pre_rt"`
	lwstPricDt    string `db:"250lwst_pric_dt"`
	lwstPricPreRt string `db:"250lwst_pric_pre_rt"`
	curPrc        string `db:"cur_prc"`
	preSig        string `db:"pre_sig"`
	predPre       string `db:"pred_pre"`
	fluRt         string `db:"flu_rt"`
	trdeQty       string `db:"trde_qty"`
	trdePre       string `db:"trde_pre"`
	favUnit       string `db:"fav_unit"`
	dstrStk       string `db:"dstr_stk"`
	dstrRt        string `db:"dstr_rt"`
}
